// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "App.tsx": {
    id: "App";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "App": typeof import("./src/App.tsx");
};